on:
  push:
    branches: [master]
  pull_request:

env:
  IMAGE: us.gcr.io/sentryio/sentry
  SENTRY_IMAGE: us.gcr.io/sentryio/sentry:${{ github.sha }}

jobs:
  self-hosted:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-volta
    - name: Setup python
      uses: actions/setup-python@b4fe97ecda6b7a5fcd2448cdbf6a8fc76b3bedb0
      with:
        python-version: 3.8.14
    - run: |
        pip install $(grep ^wheel== requirements-dev-frozen.txt)
        python setup.py bdist_wheel
        cp requirements-frozen.txt dist/
    - run: docker pull "$IMAGE"
    - run: |
        docker build \
          --cache-from "${IMAGE}:latest" \
          --build-arg "SOURCE_COMMIT=${{ github.sha }}" \
          --file docker/Dockerfile \
          --tag "${SENTRY_IMAGE}" \
          .
      timeout-minutes: 5
    - uses: actions/checkout@v3
      with:
        repository: getsentry/self-hosted
        path: self-hosted
    - run: |
        ./install.sh
        ./test.sh || (
            echo 'Test Failed!'
            docker-compose ps
            docker-compose logs
            exit 1
        )
      env:
        CI: 1
        SENTRY_TEST_HOST: http://nginx
      working-directory: self-hosted
    - run: echo TODO PUSH
